// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapi

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GetHealth200JSONResponseBodyStatus.
const (
	Ok GetHealth200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealth200JSONResponseBodyStatus enum.
func (e GetHealth200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code エラーコード
		Code string `json:"code"`

		// Message エラー内容の説明
		Message string `json:"message"`
	} `json:"error"`
}

// Grid defines model for Grid.
type Grid struct {
	Size GridSize `json:"size"`

	// Values 数字の文字列。空白時には""を使用
	Values [][]string `json:"values"`
}

// GridSize defines model for GridSize.
type GridSize struct {
	Cols int `json:"cols"`
	Rows int `json:"rows"`
}

// Point defines model for Point.
type Point struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
}

// Puzzle defines model for Puzzle.
type Puzzle struct {
	HorizontalHintGrid Grid `json:"horizontalHintGrid"`

	// HorizontalHintImage 横ヒント画像。data URI 形式（data:image/png;base64,...）
	HorizontalHintImage string `json:"horizontalHintImage"`
	VerticalHintGrid    Grid   `json:"verticalHintGrid"`

	// VerticalHintImage 縦ヒント画像。data URI 形式（data:image/png;base64,...）
	VerticalHintImage string `json:"verticalHintImage"`
}

// Quad 四角形の4頂点（左上・右上・右下・左下の順）
type Quad = []Point

// GetHealth200JSONResponseBodyStatus defines parameters for GetHealth.
type GetHealth200JSONResponseBodyStatus string

// RecognizePuzzleMultipartBody defines parameters for RecognizePuzzle.
type RecognizePuzzleMultipartBody struct {
	// HorizontalHintRegion 四角形の4頂点（左上・右上・右下・左下の順）
	HorizontalHintRegion Quad     `json:"horizontalHintRegion"`
	HorizontalHintSize   GridSize `json:"horizontalHintSize"`

	// PuzzleImage パズル画像（PNG）
	PuzzleImage openapi_types.File `json:"puzzleImage"`

	// VerticalHintRegion 四角形の4頂点（左上・右上・右下・左下の順）
	VerticalHintRegion Quad     `json:"verticalHintRegion"`
	VerticalHintSize   GridSize `json:"verticalHintSize"`
}

// RecognizePuzzleMultipartRequestBody defines body for RecognizePuzzle for multipart/form-data ContentType.
type RecognizePuzzleMultipartRequestBody RecognizePuzzleMultipartBody
